# Generated by Django 5.1.6 on 2025-05-10 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='author',
            field=models.CharField(default='Unknown', max_length=50),
            preserve_default=False,
        ),
    ]
